language: cpp
cache: ccache
sudo: required
dist: Bionic 
services:
  - docker
os:
  - linux
env:
  - JOB=PRE_COMMIT

addons:
  apt:
    packages:
      - git
      - python3-pip
      - python3-dev

before_install:
  -  python3 --version
  -  python3 -m pip --version
  -  pip3 --version
  -  sudo pip3 install -U virtualenv pre-commit pip
  -  docker pull paddlepaddle/paddle:latest

script:
  - exit_code=0
  - docker run -i --rm -v "$PWD:/py_unittest" paddlepaddle/paddle:latest /bin/bash -c
    'cd /py_unittest && bash .travis/precommit.sh && source env.sh && bash .travis/unittest.sh' || exit_code=$(( exit_code | $? ))
    exit $exit_code

notifications:
  email:
    on_success: change
    on_failure: always
